/** @format */

"use strict";

const Discord = require("discord.js"),
	Buttons = require("discord-buttons"),
	Client = require("./Classes/Client"),
	Interaction = require("./Classes/Interaction"),
	Command = require("./Classes/Command"),
	Subcommand = require("./Classes/Subcommand"),
	Event = require("./Classes/Event"),
	{
		BaseClient,
		Shard,
		ShardClientUtil,
		ShardingManager,
		WebhookClient,
		ActivityFlags,
		BitField,
		Collection,
		Constants,
		DataResolver,
		BaseManager,
		DiscordAPIError,
		HTTPError,
		MessageFlags,
		Intents,
		Permissions,
		Speaking,
		Snowflake,
		SnowflakeUtil,
		Structures,
		SystemChannelFlags,
		UserFlags,
		Util,
		version,
		ChannelManager,
		GuildChannelManager,
		GuildEmojiManager,
		GuildEmojiRoleManager,
		GuildMemberManager,
		GuildMemberRoleManager,
		GuildManager,
		ReactionManager,
		ReactionUserManager,
		MessageManager,
		PresenceManager,
		RoleManager,
		UserManager,
		discordSort,
		escapeMarkdown,
		fetchRecommendedShards,
		resolveColor,
		resolveString,
		splitMessage,
		Application,
		Base,
		Activity,
		APIMessage,
		BaseGuildEmoji,
		CategoryChannel,
		Channel,
		ClientApplication,
		ClientUser,
		Collector,
		DMChannel,
		Emoji,
		Guild,
		GuildAuditLogs,
		GuildChannel,
		GuildEmoji,
		GuildMember,
		GuildPreview,
		GuildTemplate,
		Integration,
		Invite,
		Message,
		MessageAttachment,
		MessageCollector,
		MessageEmbed,
		MessageMentions,
		MessageReaction,
		NewsChannel,
		PermissionOverwrites,
		Presence,
		ClientPresence,
		ReactionCollector,
		ReactionEmoji,
		RichPresenceAssets,
		Role,
		StoreChannel,
		Team,
		TeamMember,
		TextChannel,
		User,
		VoiceChannel,
		VoiceRegion,
		VoiceState,
		Webhook,
		WebSocket
	} = Discord;

module.exports = {
	Discord,
	Client,
	BaseClient,
	Shard,
	ShardClientUtil,
	ShardingManager,
	WebhookClient,
	ActivityFlags,
	BitField,
	Collection,
	Constants,
	DataResolver,
	BaseManager,
	DiscordAPIError,
	HTTPError,
	MessageFlags,
	Intents,
	Permissions,
	Speaking,
	Snowflake,
	SnowflakeUtil,
	Structures,
	SystemChannelFlags,
	UserFlags,
	Util,
	version,
	ChannelManager,
	GuildChannelManager,
	GuildEmojiManager,
	GuildEmojiRoleManager,
	GuildMemberManager,
	GuildMemberRoleManager,
	GuildManager,
	ReactionManager,
	ReactionUserManager,
	MessageManager,
	PresenceManager,
	RoleManager,
	UserManager,
	discordSort,
	escapeMarkdown,
	fetchRecommendedShards,
	resolveColor,
	resolveString,
	splitMessage,
	Application,
	Base,
	Activity,
	APIMessage,
	BaseGuildEmoji,
	CategoryChannel,
	Channel,
	ClientApplication,
	ClientUser,
	Collector,
	DMChannel,
	Emoji,
	Guild,
	GuildAuditLogs,
	GuildChannel,
	GuildEmoji,
	GuildMember,
	GuildPreview,
	GuildTemplate,
	Integration,
	Invite,
	Message,
	MessageAttachment,
	MessageCollector,
	MessageEmbed,
	MessageMentions,
	MessageReaction,
	NewsChannel,
	PermissionOverwrites,
	Presence,
	ClientPresence,
	ReactionCollector,
	ReactionEmoji,
	RichPresenceAssets,
	Role,
	StoreChannel,
	Team,
	TeamMember,
	TextChannel,
	User,
	VoiceChannel,
	VoiceRegion,
	VoiceState,
	Webhook,
	WebSocket,
	Interaction,
	Command,
	Subcommand,
	Event,
	MessageButton: Buttons.MessageButton
};

const path = require("path");

const client = new Client(
	{
		token: "",
		prefix: "!",
		builtInHelpCommand: true,
		emitMessageOnInteraction: true
	},
	{
		cmds: path.join(__dirname, "Commands"),
		events: path.join(__dirname, "Events"),
		subs: path.join(__dirname, "Subcommands")
	}
);
